/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package safefolder;

import javax.swing.JOptionPane;
import java.io.File;

/**
 *
 * @author Prabhjeet
 */
public class SafeFolder extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public SafeFolder() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SafeFolder");
        setMinimumSize(new java.awt.Dimension(338, 250));
        setPreferredSize(new java.awt.Dimension(338, 250));
        setSize(new java.awt.Dimension(338, 250));

        jPanel1.setLayout(null);
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(50, 170, 200, 20);

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("DECRYPT FOLDER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(130, 100, 170, 40);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("ENCRYPT FOLDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(130, 30, 170, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/safefolder/data_encryption.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 140, 150);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        filechooser om=new filechooser();
        String s = om.selectPath();
        om.setDefaultCloseOperation(EXIT_ON_CLOSE);
        File folder=new File(s);
        String pwd="";
        while(pwd.length()<8)
        {
        pwd=JOptionPane.showInputDialog("Please Enter Password\n(Minimum length-8)");        
        }
        listFilesforFolder(folder,pwd);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void listFilesforFolder(File folder,String pwd)
    {
        
        
        for(File fileEntry:folder.listFiles()){
            if(fileEntry.isDirectory()){
                listFilesforFolder(fileEntry,pwd);
            }
            else{
               try{
                   jProgressBar1.setVisible(true);
                   jProgressBar1.setIndeterminate(true);
                AESFileEncryption.encrypt(fileEntry.getPath(), pwd);
                }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Encryption failed."+e);
             jProgressBar1.setVisible(false);
            return;
            } 
            }
        } jProgressBar1.setVisible(false);
    }
    private  void listFilesforFolder1(File folder,String pwd)
    {
       
        
        for(File fileEntry:folder.listFiles()){
            if(fileEntry.isDirectory()){
                listFilesforFolder1(fileEntry,pwd);
            }
            else{
               try{
                   jProgressBar1.setVisible(true);
                   jProgressBar1.setIndeterminate(true);
                AESFileDecryption.decrypt(fileEntry.getPath(), pwd);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Decryption failed.");
            jProgressBar1.setVisible(false);
            return;
            } 
            }
        }
        jProgressBar1.setVisible(false);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        filechooser om=new filechooser();
        String s=om.selectPath();
        om.setDefaultCloseOperation(EXIT_ON_CLOSE);
        File folder=new File(s);
        String pwd="";
        while(pwd.length()<8)
        {
        pwd=JOptionPane.showInputDialog("Please Enter Password\n(Minimum length-8)");
        
        }
        listFilesforFolder1(folder,pwd);
    }//GEN-LAST:event_jButton2ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //BackgroundImageJFrame bij=new BackgroundImageJFrame();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
               
            }
                

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SafeFolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SafeFolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SafeFolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SafeFolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SafeFolder().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

}
